annotation: genes
customAnnotation: false
customFeatures:
- Input/FeatureBeds/DNASEmesc_SRX1452763.05.bed
- Input/FeatureBeds/DNASEmesc_SRX1452763.05.bed
datasets:
- DLBCLPB
insertionFile:
- Input/BEDInsertionTesting/DLBCLPB.BED
multest_correction:
- bonferroni
mutagenesis_method:
- predefinedFeatures
outputDir: Output
snakemakeRule: --cores 8
transposonSystem:
- PB
